-- MySQL Script generated by MySQL Workbench
-- 12/09/14 09:46:58
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS ofc DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE ofc ;

-- -----------------------------------------------------
-- Table ofc.`institute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`institute` ;

CREATE TABLE IF NOT EXISTS ofc.`institute` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email_suffix` VARCHAR(45) NOT NULL,
  `third_party_auth` TINYINT(1) NULL,
  `provider` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`country` ;

CREATE TABLE IF NOT EXISTS ofc.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `country_code` VARCHAR(3) NULL,
  `iso_code` VARCHAR(3) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`state` ;

CREATE TABLE IF NOT EXISTS ofc.`state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_state_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_state_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES ofc.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`pincode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`pincode` ;

CREATE TABLE IF NOT EXISTS ofc.`pincode` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pincode` VARCHAR(45) NULL,
  `state_id` INT NOT NULL,
  PRIMARY KEY (`id`, `state_id`),
  INDEX `fk_pincode_state1_idx` (`state_id` ASC),
  CONSTRAINT `fk_pincode_state1`
    FOREIGN KEY (`state_id`)
    REFERENCES ofc.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`address` ;

CREATE TABLE IF NOT EXISTS ofc.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `line_one` VARCHAR(45) NOT NULL,
  `line_two` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `version` INT NULL,
  `pincode_id` INT NOT NULL,
  `pincode_state_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pincode_id`, `pincode_state_id`),
  INDEX `fk_address_pincode1_idx` (`pincode_id` ASC, `pincode_state_id` ASC),
  CONSTRAINT `fk_address_pincode1`
    FOREIGN KEY (`pincode_id` , `pincode_state_id`)
    REFERENCES ofc.`pincode` (`id` , `state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`campus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`campus` ;

CREATE TABLE IF NOT EXISTS ofc.`campus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `institute_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `address_pincode_id` INT NOT NULL,
  `address_pincode_state_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_campus_institute_idx` (`institute_id` ASC),
  INDEX `fk_campus_address1_idx` (`address_id` ASC, `address_pincode_id` ASC, `address_pincode_state_id` ASC),
  CONSTRAINT `fk_campus_institute`
    FOREIGN KEY (`institute_id`)
    REFERENCES ofc.`institute` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campus_address1`
    FOREIGN KEY (`address_id` , `address_pincode_id` , `address_pincode_state_id`)
    REFERENCES ofc.`address` (`id` , `pincode_id` , `pincode_state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`location` ;

CREATE TABLE IF NOT EXISTS ofc.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lng` VARCHAR(45) NULL,
  `lat` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`place` ;

CREATE TABLE IF NOT EXISTS ofc.`place` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `google_place_id` VARCHAR(45) NULL,
  `location_id` INT NOT NULL,
  `pincode_id` INT NOT NULL,
  `pincode_state_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_place_location1_idx` (`location_id` ASC),
  INDEX `fk_place_pincode1_idx` (`pincode_id` ASC, `pincode_state_id` ASC),
  CONSTRAINT `fk_place_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES ofc.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_place_pincode1`
    FOREIGN KEY (`pincode_id` , `pincode_state_id`)
    REFERENCES ofc.`pincode` (`id` , `state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`user` ;

CREATE TABLE IF NOT EXISTS ofc.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `account_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `gender` TINYINT(1) NULL,
  `verified` TINYINT(1) NULL,
  `hash` VARCHAR(100) NULL,
  `created_date` DATETIME NOT NULL,
  `updated_date` TIMESTAMP NOT NULL,
  `institute_id` INT NOT NULL,
  PRIMARY KEY (`id`, `institute_id`),
  INDEX `fk_user_institute1_idx` (`institute_id` ASC),
  CONSTRAINT `fk_user_institute1`
    FOREIGN KEY (`institute_id`)
    REFERENCES ofc.`institute` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`role` ;

CREATE TABLE IF NOT EXISTS ofc.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`user_has_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`user_has_role` ;

CREATE TABLE IF NOT EXISTS ofc.`user_has_role` (
  `user_id` INT(11) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_has_role_role1_idx` (`role_id` ASC),
  INDEX `fk_user_has_role_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES ofc.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES ofc.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`post` ;

CREATE TABLE IF NOT EXISTS ofc.`post` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(500) NOT NULL,
  `content` MEDIUMTEXT NULL,
  `reply_email` VARCHAR(45) NULL,
  `reply_phone` VARCHAR(45) NULL,
  `reply_watspp` VARCHAR(45) NULL,
  `created_date` DATETIME NOT NULL,
  `updated_date` TIMESTAMP NULL,
  `user_id` INT(11) NOT NULL,
  `user_institute_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_user1_idx` (`user_id` ASC, `user_institute_id` ASC),
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_id` , `user_institute_id`)
    REFERENCES ofc.`user` (`id` , `institute_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`industry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`industry` ;

CREATE TABLE IF NOT EXISTS ofc.`industry` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`industry_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`industry_roles` ;

CREATE TABLE IF NOT EXISTS ofc.`industry_roles` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `industry_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_job_roles_industry1_idx` (`industry_id` ASC),
  CONSTRAINT `fk_job_roles_industry1`
    FOREIGN KEY (`industry_id`)
    REFERENCES ofc.`industry` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`job_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`job_post` ;

CREATE TABLE IF NOT EXISTS ofc.`job_post` (
  `to` INT NOT NULL,
  `from` INT NOT NULL,
  `salary_to` DOUBLE NULL,
  `salary_from` DOUBLE NULL,
  `post_id` INT(11) NOT NULL,
  PRIMARY KEY (`to`),
  INDEX `fk_job_post_post1_idx` (`post_id` ASC),
  CONSTRAINT `fk_job_post_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES ofc.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`job_post_has_job_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`job_post_has_job_roles` ;

CREATE TABLE IF NOT EXISTS ofc.`job_post_has_job_roles` (
  `job_post_to` INT NOT NULL,
  `job_roles_id` INT(11) NOT NULL,
  PRIMARY KEY (`job_post_to`, `job_roles_id`),
  INDEX `fk_job_post_has_job_roles_job_roles1_idx` (`job_roles_id` ASC),
  INDEX `fk_job_post_has_job_roles_job_post1_idx` (`job_post_to` ASC),
  CONSTRAINT `fk_job_post_has_job_roles_job_post1`
    FOREIGN KEY (`job_post_to`)
    REFERENCES ofc.`job_post` (`to`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_post_has_job_roles_job_roles1`
    FOREIGN KEY (`job_roles_id`)
    REFERENCES ofc.`industry_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`city` ;

CREATE TABLE IF NOT EXISTS ofc.`city` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `state_id` INT NOT NULL,
  PRIMARY KEY (`id`, `state_id`),
  INDEX `fk_city_state1_idx` (`state_id` ASC),
  CONSTRAINT `fk_city_state1`
    FOREIGN KEY (`state_id`)
    REFERENCES ofc.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`job_post_has_city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`job_post_has_city` ;

CREATE TABLE IF NOT EXISTS ofc.`job_post_has_city` (
  `job_post_to` INT NOT NULL,
  `city_id` INT(11) NOT NULL,
  `city_state_id` INT NOT NULL,
  PRIMARY KEY (`job_post_to`, `city_id`, `city_state_id`),
  INDEX `fk_job_post_has_city_city1_idx` (`city_id` ASC, `city_state_id` ASC),
  INDEX `fk_job_post_has_city_job_post1_idx` (`job_post_to` ASC),
  CONSTRAINT `fk_job_post_has_city_job_post1`
    FOREIGN KEY (`job_post_to`)
    REFERENCES ofc.`job_post` (`to`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_post_has_city_city1`
    FOREIGN KEY (`city_id` , `city_state_id`)
    REFERENCES ofc.`city` (`id` , `state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ofc.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS ofc.`comments` ;

CREATE TABLE IF NOT EXISTS ofc.`comments` (
  `id` INT(11) NOT NULL,
  `comment` TEXT NULL,
  `created_date` DATETIME NULL,
  `updated_date` TIMESTAMP NULL,
  `post_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `user_institute_id` INT NOT NULL,
  PRIMARY KEY (`id`, `post_id`, `user_id`, `user_institute_id`),
  INDEX `fk_comments_post1_idx` (`post_id` ASC),
  INDEX `fk_comments_user1_idx` (`user_id` ASC, `user_institute_id` ASC),
  CONSTRAINT `fk_comments_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES ofc.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_user1`
    FOREIGN KEY (`user_id` , `user_institute_id`)
    REFERENCES ofc.`user` (`id` , `institute_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
